### ISSUE TITLE
What to put at the Database Host?

### ISSUE THREAD

**Issue by thepenguinthatwants** [linuxserver/docker-lychee#26]
Hi LinuxServer!

I am trying to figure out how to use lychee on my traefik stack. For now I can start it and navigate to the installation page where is asks more details about database.

Filling the information seems to work but it doesnt allow me to go forward. Not sure what to put into the database host nor that sure if lychee and mariadb is really connected.

Host OS 
Debian 9

Here is my docker-compose.yml
```

---
version: "3"
services:
  lychee:
    image: linuxserver/lychee
    container_name: lychee
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Stockholm
    volumes:
      - ./config:/config
      - ./pictures:/pictures
    restart: unless-stopped
    networks:
      - web
      - lychee
    labels:
      - traefik.enable=true
      - traefik.port=80
      - traefik.backend=lychee
      - traefik.frontend.rule=Host:lychee.example.xyz
      - traefik.docker.network=web

  db:
    image: mariadb
    container_name: lychee_db
    restart: unless-stopped
    networks:
     - lychee
    volumes:
     - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: lychee
      MYSQL_DATABASE: lychee
      MYSQL_USER: lychee
      MYSQL_PASSWORD: lychee
    labels:
      - traefik.enable=false


networks:
  web:
    external: true
  lychee:
    external: false




```
