### ISSUE TITLE
Automatic import according to Lychee docs not working

### ISSUE THREAD

**Issue by twatzl** [linuxserver/docker-lychee#38]
Hi, 

I am trying to set up the automatic import according to the lychee docs here https://lycheeorg.github.io/docs/faq.html#can-i-set-up-lychee-to-watch-a-folder-for-new-images-and-automatically-add-them-to-albums

However when executing `php artisan` in the docker container it does not work
```
# docker exec -it lychee-compose_lychee_1 /bin/bash
root@7d731a248dac:/# php artisan
Could not open input file: artisan
```

docker-compose.yml:
```
# Use root/example as user/password credentials
version: '3.1'

services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ...
      MYSQL_DATABASE: lychee 
      MYSQL_USER: lychee
      MYSQL_PASSWORD: ...
    networks:
      - lychee-internal
    volumes:
      - lychee-db:/var/lib/mysql
    
  lychee:
    image: linuxserver/lychee:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Vienna    
    networks:
      - lychee-internal
      - reverse-proxy-network
    volumes:
      - lychee-uploads:/uploads/:Z
      - lychee-config:/config/:Z
      - lychee-pictures:/pictures/:Z
        #    ports:
        #      - 8090:80
    labels:
      /** labels for reverse proxy **/
    restart: unless-stopped


/** networks and volumes are defined here **/
```
