### ISSUE TITLE
 Lychee does not create the database.

### ISSUE THREAD

**Issue by dexter74** [linuxserver/docker-lychee#43]
Hello,
 Lychee does not create the database.

Docker-compose is default: 
````
version: "3"
services:
  mariadb:
    image: ghcr.io/linuxserver/mariadb:latest
    container_name: lychee_mariadb
    restart: always
    volumes:
      - mariadb:/config
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=lychee
      - MYSQL_USER=lychee
      - MYSQL_PASSWORD=dbpassword
      - PGID=1000
      - PUID=1000
      - TZ=Europe/London
  lychee:
    image: ghcr.io/linuxserver/lychee:latest
    container_name: lychee
    restart: always
    depends_on:
      - mariadb
    volumes:
      - config:/config
      - pictures:/pictures
    environment:
      - DB_HOST=mariadb
      - DB_USER=lychee
      - DB_PASS=dbpassword
      - DB_NAME=lychee
      - DB_PORT=3306
      - PGID=1000
      - PUID=1000
      - TZ=Europe/London
    ports:
      - 80:80
      
volumes:
  mariadb:
  config:
  pictures:
````

--------------------------

````
APP_NAME=Lychee
APP_ENV=production
APP_KEY=
APP_DEBUG=false
APP_URL=http://localhost

# enable or disable debug bar. By default it is disabled.
DEBUGBAR_ENABLED=false

LOG_CHANNEL=stack

##############################################################################
# IMPORTANT: To migrate from Lychee v3 you *MUST* use the same MySQL/MariaDB #
#            server as v3.                                                   #
##############################################################################

# Table prefix (e.g. lychee_) of a Lychee v3 instance for migration
DB_OLD_LYCHEE_PREFIX=

# DB_CONNECTION can be sqlite, mysql or pgsql. For sqlite the other entries are
# not required, but an existing sqlite3 database may be specified if desired. In
# this case, please use an absolute path. DB_DATABASE may be omitted but should
# *not* be left blank.
DB_CONNECTION=sqlite
DB_HOST=
DB_PORT=
#DB_DATABASE=
DB_USERNAME=
DB_PASSWORD=
DB_LOG_SQL=false

TIMEZONE=UTC

# folders in which the files will be stored
# LYCHEE_DIST="/var/www/html/Lychee-Laravel/public/dist/"
# LYCHEE_UPLOADS="/var/www/html/Lychee-Laravel/public/uploads/"

# url to access those files
# LYCHEE_DIST_URL="dist/"
# LYCHEE_UPLOADS_URL="uploads/"

BROADCAST_DRIVER=log
CACHE_DRIVER=file
SESSION_DRIVER=file
SESSION_LIFETIME=120
QUEUE_DRIVER=sync

SECURITY_HEADER_HSTS_ENABLE=false

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_DRIVER=smtp
MAIL_HOST=
MAIL_PORT=
MAIL_USERNAME=
MAIL_PASSWORD=
MAIL_ENCRYPTION=

PUSHER_APP_ID=
PUSHER_APP_KEY=
PUSHER_APP_SECRET=
PUSHER_APP_CLUSTER=mt1

MIX_PUSHER_APP_KEY="${PUSHER_APP_KEY}"
MIX_PUSHER_APP_CLUSTER="${PUSHER_APP_CLUSTER}"
````

![image](https://user-images.githubusercontent.com/35907/106692849-90666080-65d5-11eb-854e-2381c8fc7538.png)
