### ISSUE TITLE
volumes don't map correctly on filesystem

### ISSUE THREAD

**Issue by ghost** [linuxserver/docker-lychee#49]
Hi,

I'm using previous docker-compose file, that I've found in your documentation (current one doesn't work - shows some ownership issues), it looks like this:

```
version: "3"
services:
  mariadb:
    image: ghcr.io/linuxserver/mariadb:latest
    container_name: lychee_mariadb
    restart: always
    volumes:
      - /mnt/ops_appdata/lychee_mariadb:/mnt/lychee_mdb_config
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=lychee
      - MYSQL_USER=lychee
      - MYSQL_PASSWORD=dbpassword
      - PGID=1000
      - PUID=1000
      - TZ=Europe/London
  lychee:
    image: ghcr.io/linuxserver/lychee:latest
    container_name: lychee
    restart: always
    depends_on:
      - mariadb
    volumes:
      - /mnt/ops_appdata/lychee_config:/mnt/lychee_config
      - /mnt/multimedia_pictures:/mnt/lychee_data
    environment:
      - DB_HOST=mariadb
      - DB_USERNAME=lychee
      - DB_PASSWORD=dbpassword
      - DB_DATABASE=lychee
      - DB_PORT=3306
      - PGID=1000
      - PUID=1000
      - TZ=Europe/London
    ports:
      - 80:80
```

An instance created with this file works fine, except the fact, that all of mapped directories are empty:

```
docker_admin@docker_test:~$ ls /mnt/ops_appdata/lychee_mariadb
docker_admin@docker_test:~$ ls /mnt/ops_appdata/lychee_config
docker_admin@docker_test:~$ ls /mnt/multimedia_pictures
```

There is nothing inside them and I would like to fix it for the sake of backup. Could you please help me debug this problem?
