### ISSUE TITLE
I can't upload any picture - 500 Internal Server Error

### ISSUE THREAD

**Issue by ghost** [linuxserver/docker-lychee#50]
I have fresh instance created with docker-compose file:

```
version: "3"
services:
  mariadb:
    image: ghcr.io/linuxserver/mariadb:arm64v8-latest
    container_name: lychee_mariadb
    restart: always
    volumes:
      - /mnt/ops_appdata/lychee_mariadb:/config
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=lychee
      - MYSQL_USER=lychee
      - MYSQL_PASSWORD=dbpassword
      - PGID=1000
      - PUID=1000
      - TZ=Europe/London
  lychee:
    image: ghcr.io/linuxserver/lychee:arm64v8-latest
    container_name: lychee
    restart: always
    depends_on:
      - mariadb
    volumes:
      - /mnt/ops_appdata/lychee_config:/config
      - /mnt/multimedia_pictures:/pictures
    environment:
      - DB_HOST=mariadb
      - DB_USERNAME=lychee
      - DB_PASSWORD=dbpassword
      - DB_DATABASE=lychee
      - DB_PORT=3306
      - PGID=1000
      - PUID=1000
      - TZ=Europe/London
    ports:
      - 80:80
```

While I'm trying to upload any image, there is an error saying: **Server returned an unknown response**
After inspecting browsers console I just find: **500 Internal Server Error**

Could you please help me debug this problem?
